/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package keyCompetition;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pini
 */
public class keyFrame extends javax.swing.JFrame {
       private Client client;
    /**
     * Creates new form keyFrame
     */
    public keyFrame() {
        initComponents();
        
        client = new Client("127.0.0.1", 1235);  // Modifica l'indirizzo e la porta se necessario
        UsernamePage.setVisible(true);
        WordsOption.setVisible(false);
        KeyDigitation.setVisible(false);
        Ranking.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UsernamePage = new javax.swing.JPanel();
        UserText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sfondo1 = new javax.swing.JLabel();
        WordsOption = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Button10 = new javax.swing.JButton();
        Button20 = new javax.swing.JButton();
        Button30 = new javax.swing.JButton();
        sfondo2 = new javax.swing.JLabel();
        KeyDigitation = new javax.swing.JPanel();
        digitationText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sfondo3 = new javax.swing.JLabel();
        Ranking = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rankTable = new javax.swing.JTable();
        sfondo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(282, 370));

        UsernamePage.setBackground(new java.awt.Color(51, 51, 51));
        UsernamePage.setOpaque(false);
        UsernamePage.setPreferredSize(new java.awt.Dimension(281, 370));
        UsernamePage.setLayout(null);

        UserText.setBackground(new java.awt.Color(217, 217, 217));
        UserText.setOpaque(false);
        UserText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTextActionPerformed(evt);
            }
        });
        UsernamePage.add(UserText);
        UserText.setBounds(56, 198, 170, 42);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/text1.png"))); // NOI18N
        UsernamePage.add(jLabel2);
        jLabel2.setBounds(51, 41, 179, 51);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/textField1.png"))); // NOI18N
        UsernamePage.add(jLabel1);
        jLabel1.setBounds(51, 157, 179, 90);

        sfondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/Username.png"))); // NOI18N
        UsernamePage.add(sfondo1);
        sfondo1.setBounds(0, 0, 282, 370);

        WordsOption.setBackground(new java.awt.Color(51, 51, 51));
        WordsOption.setPreferredSize(new java.awt.Dimension(282, 370));
        WordsOption.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/text2.png"))); // NOI18N
        WordsOption.add(jLabel4);
        jLabel4.setBounds(51, 41, 179, 51);

        Button10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/10.png"))); // NOI18N
        Button10.setContentAreaFilled(false);
        Button10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button10ActionPerformed(evt);
            }
        });
        WordsOption.add(Button10);
        Button10.setBounds(100, 142, 81, 37);

        Button20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/20.png"))); // NOI18N
        Button20.setContentAreaFilled(false);
        Button20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button20ActionPerformed(evt);
            }
        });
        WordsOption.add(Button20);
        Button20.setBounds(100, 205, 81, 37);

        Button30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/30.png"))); // NOI18N
        Button30.setContentAreaFilled(false);
        Button30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button30ActionPerformed(evt);
            }
        });
        WordsOption.add(Button30);
        Button30.setBounds(100, 268, 81, 37);

        sfondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/Username.png"))); // NOI18N
        WordsOption.add(sfondo2);
        sfondo2.setBounds(0, 0, 282, 370);

        KeyDigitation.setBackground(new java.awt.Color(51, 51, 51));
        KeyDigitation.setPreferredSize(new java.awt.Dimension(729, 469));
        KeyDigitation.setLayout(null);

        digitationText.setBackground(new java.awt.Color(217, 217, 217));
        digitationText.setBorder(null);
        digitationText.setOpaque(false);
        digitationText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                digitationTextActionPerformed(evt);
            }
        });
        KeyDigitation.add(digitationText);
        digitationText.setBounds(37, 42, 654, 213);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/currentWord.png"))); // NOI18N
        KeyDigitation.add(jLabel5);
        jLabel5.setBounds(37, 276, 229, 62);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/digitation.png"))); // NOI18N
        KeyDigitation.add(jLabel3);
        jLabel3.setBounds(37, 42, 654, 213);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/errors.png"))); // NOI18N
        KeyDigitation.add(jLabel6);
        jLabel6.setBounds(462, 274, 229, 62);

        userText.setBackground(new java.awt.Color(217, 217, 217));
        userText.setOpaque(false);
        KeyDigitation.add(userText);
        userText.setBounds(37, 354, 654, 58);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/text3.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        KeyDigitation.add(jLabel7);
        jLabel7.setBounds(37, 354, 654, 58);

        sfondo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/keyDigitation.png"))); // NOI18N
        KeyDigitation.add(sfondo3);
        sfondo3.setBounds(0, 0, 729, 469);

        Ranking.setBackground(new java.awt.Color(51, 51, 51));
        Ranking.setPreferredSize(new java.awt.Dimension(421, 370));
        Ranking.setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/text4.png"))); // NOI18N
        Ranking.add(jLabel8);
        jLabel8.setBounds(36, 41, 179, 50);

        jScrollPane1.setBackground(new java.awt.Color(217, 217, 217));

        rankTable.setBackground(new java.awt.Color(217, 217, 217));
        rankTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(rankTable);

        Ranking.add(jScrollPane1);
        jScrollPane1.setBounds(36, 128, 349, 197);

        sfondo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/keyCompetition/Ranking.png"))); // NOI18N
        Ranking.add(sfondo4);
        sfondo4.setBounds(0, 0, 421, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsernamePage, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(WordsOption, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(KeyDigitation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(UsernamePage, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(WordsOption, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(KeyDigitation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Ranking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void UserTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTextActionPerformed
        // TODO add your handling code here:
        String username = UserText.getText();
    client.sendUsername(username);
    // Passa alla schermata successiva
    WordsOption.setVisible(true);
    UsernamePage.setVisible(false);
    }//GEN-LAST:event_UserTextActionPerformed

    private void digitationTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_digitationTextActionPerformed
        // TODO add your handling code here:
        String text = digitationText.getText();
    client.sendTypingData(text);
    }//GEN-LAST:event_digitationTextActionPerformed

    private void Button10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button10ActionPerformed
        // TODO add your handling code here:
        WordsOption.setVisible(false);
        KeyDigitation.setVisible(true);
    }//GEN-LAST:event_Button10ActionPerformed

    private void Button20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button20ActionPerformed

    private void Button30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button30ActionPerformed
private void updateRanking() {
    String ranking = client.getRanking();
    // Aggiorna la tabella con la classifica
    String[] rows = ranking.split("\n");  // Assume che il server invii la classifica riga per riga
    for (String row : rows) {
        // Aggiungi la riga alla tabella
        ((DefaultTableModel) rankTable.getModel()).addRow(new Object[] {row});
    }
}

private void closeConnection() {
        client.close();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            keyFrame frame = new keyFrame();
            frame.setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button10;
    private javax.swing.JButton Button20;
    private javax.swing.JButton Button30;
    private javax.swing.JPanel KeyDigitation;
    private javax.swing.JPanel Ranking;
    private javax.swing.JTextField UserText;
    private javax.swing.JPanel UsernamePage;
    private javax.swing.JPanel WordsOption;
    private javax.swing.JTextField digitationText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable rankTable;
    private javax.swing.JLabel sfondo1;
    private javax.swing.JLabel sfondo2;
    private javax.swing.JLabel sfondo3;
    private javax.swing.JLabel sfondo4;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
